apiVersion: v1
kind: Pod
metadata:
    name: vaccel-sidecar-pod
spec:
    containers:
        - name: vaccel-agent
          image: harbor.nbfc.io/nubificus/vaccel-torch-bert-example-agent:x86_64
          volumeMounts:
              - name: vaccel-sock
                mountPath: /var/run/vaccel

        - name: vaccel-client
          image: harbor.nbfc.io/nubificus/vaccel-torch-bert-example:x86_64
          command: ["./build/classifier"]
          args: ["-m", "cnn_trace.pt", "-v", "bert_cased_vocab.txt", "-f", "/data/tweets.txt"]
          volumeMounts:
              - name: vaccel-sock
                mountPath: /var/run/vaccel
              - name: tweets
                mountPath: /data

    volumes:
        - name: vaccel-sock
          emptyDir: {}
        - name: tweets
          hostPath:
            path: /data
