apiVersion: v1
kind: Service
metadata:
  name: vaccel-metrics
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vaccel-client
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: {{ .Values.service.nodePort }}
